services:
  registry:
    image: registry:2
    container_name: private-registry
    ports:
      - 5001:5000
    volumes:
      - ./registry_data:/var/lib/registry
    restart: unless-stopped

volumes:
  registry_data:
