services:
  api-gateway:
    image: localhost:5001/banking-service
    container_name: api-gateway
    ports:
      - 8080:8080
    restart: unless-stopped
  database:
    image: mongo
    container_name: database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      # - bank_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

volumes:
  bank_data:
